# Generated by Django 4.2.2 on 2023-06-14 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_imageproduct_image_alter_imageproduct_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageproduct',
            name='image',
            field=models.ImageField(upload_to='product/'),
        ),
    ]
