name: Grocery CI
on:
  push:
    branches: ["main"]
jobs:
  build:
    name: "build and test"
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        python-version: [3.7,3.8,3.9]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version}}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: | 
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        echo " install dependencies completed with success wait for deploy jobs ....."